### ISSUE TITLE
No `libs/` in output dir `.site/` for the example content

### ISSUE THREAD

**Issue by kamalx** [signalkuppe/pequeno#6]
I get this error about lazyload.js not loading on the provided example site/content.

![image](https://user-images.githubusercontent.com/94972/228231979-bca12db4-e580-4342-bf37-a1444ff9199f.png)

https://github.com/signalkuppe/pequeno/blob/main/example/components/ui/Image/index.jsx#L27

It turns out these files aren't included in the repo. It would be great if you could include these files as well. :)

Thanks for your work. I've just started exploring this and I am hopeful this project can help me with my simple needs.

**Comment by kamalx** [comment]
Hi there! Never mind, found the file and the relevant part of doc in the README. :)

However, it's still not very clear to me how static assets like images, js, and css will get copied to the build dir for a site I start from scratch in `src/`. A tiny addition to the example for this would help immensely. Thank you!

**Comment by signalkuppe** [comment]
hi @kamalx, sure, I'll try to improve the docs about this feature. Thanks for reporting this
